### PR TITLE
Added legend hide/show click listener.

### PR DESCRIPTION
**Pull request by RazvanML**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Feature: ability to listen on legend show/hide.

* **What is the current behavior?** (You can also link to an open issue here)

The server was not notified about user click events

* **What is the new behavior (if this is a feature change)?**

The server can listen on a hide/show data-set event.

* **Other information**:

### CODE REVIEW

**Comment by moberwasserlechner** [comment]
Could you please create a view in the demo demonstrating your PR. thx

**Comment by RazvanML** [comment]
Demo is added for the first chart, but it shall work with all the charts.

**Comment by RazvanML** [comment]
Michael, is there anything I shall add to get the pull approved?

**Comment by moberwasserlechner** [comment]
No thanks for your work. I will approve it asap but it will take another few days because I have to finish a important project till next week ;)

**Pull request merged**
