### PR TITLE
Feature/39 user callbacks

### PR DESCRIPTION
**Pull request by kegoe**
Introduction of JavaScript callbacks, solving ticks tooltip formatting (#39, #48)

### CODE REVIEW

**Comment by dyorgio** [comment]
Hey, how about update some test/example to use this new way to pass functions do chart.js?

**Comment by kegoe** [comment]
Thanks... some very simple examples can be found here:
https://github.com/moberwasserlechner/vaadin-chartjs-demo/pull/5

**Comment by moberwasserlechner** [comment]
Thanks for this looks cool. Is it ready to be merged?

**Comment by moberwasserlechner** [comment]
Sry for the silence. You say that 

> The approach is pretty much the same as the one Vaadin Charts is using internally.

Is it the same. Could there be problem with the licence Vaadin Charts is commerical and incompatible with MIT.

Do you or anyone else know?

**Comment by dyorgio** [comment]
My 2 cents:

Approach is same, source doesn't.

I don't believe that Vaadin has the patent of it, because it is a common way to work with distributed services (client/server arch).

Conclusion: no licensing problem.

Some time ago Oracle (Java) tried to issue Google (Android) using a common way to handle IO:
```java
int readed;
byte[] buffer =  new byte[1024];
while ((readed = input.read(buffer)) != -1) {
   // use data
}
```

Oracle lost, because it is a common way to work with Java IO.

**Comment by moberwasserlechner** [comment]
@kegoe @dyorgio thanks for your answers.

**Pull request merged**
